/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-chat' : '&#xe000;',
			'icon-facebook' : '&#xe001;',
			'icon-facebook-2' : '&#xe002;',
			'icon-facebook-3' : '&#xe003;',
			'icon-twitter' : '&#xe004;',
			'icon-twitter-2' : '&#xe005;',
			'icon-twitter-3' : '&#xe006;',
			'icon-feed' : '&#xe007;',
			'icon-feed-2' : '&#xe008;',
			'icon-feed-3' : '&#xe009;',
			'icon-youtube' : '&#xe00a;',
			'icon-youtube-2' : '&#xe00b;',
			'icon-vimeo' : '&#xe00c;',
			'icon-vimeo2' : '&#xe00d;',
			'icon-vimeo-2' : '&#xe00e;',
			'icon-android' : '&#xe00f;',
			'icon-skype' : '&#xe010;',
			'icon-firefox' : '&#xe011;',
			'icon-IE' : '&#xe012;',
			'icon-chrome' : '&#xe013;',
			'icon-opera' : '&#xe014;',
			'icon-tumblr' : '&#xe015;',
			'icon-tumblr-2' : '&#xe016;',
			'icon-twitter-4' : '&#xe017;',
			'icon-camera' : '&#xe018;',
			'icon-comment' : '&#xe019;',
			'icon-aperture' : '&#xe01a;',
			'icon-aperture-alt' : '&#xe01b;',
			'icon-chart' : '&#xe01c;',
			'icon-chart-alt' : '&#xe01d;',
			'icon-lock-stroke' : '&#xe01f;',
			'icon-lock-fill' : '&#xe01e;',
			'icon-unlock-stroke' : '&#xe020;',
			'icon-unlock-fill' : '&#xe021;',
			'icon-tag-stroke' : '&#xe022;',
			'icon-tag-fill' : '&#xe023;',
			'icon-download' : '&#xe024;',
			'icon-upload' : '&#xe025;',
			'icon-map-pin-alt' : '&#xe026;',
			'icon-map-pin-fill' : '&#xe027;',
			'icon-map-pin-stroke' : '&#xe028;',
			'icon-paperclip' : '&#xe029;',
			'icon-arrow-down-alt1' : '&#xe02a;',
			'icon-arrow-up-alt1' : '&#xe02b;',
			'icon-arrow-right-alt1' : '&#xe02c;',
			'icon-arrow-left-alt1' : '&#xe02d;',
			'icon-arrow-left' : '&#xe02e;',
			'icon-arrow-right' : '&#xe02f;',
			'icon-arrow-up' : '&#xe030;',
			'icon-arrow-down' : '&#xe031;',
			'icon-left-quote' : '&#xe032;',
			'icon-right-quote' : '&#xe033;',
			'icon-cursor' : '&#xe034;',
			'icon-check-alt' : '&#xe035;',
			'icon-x' : '&#xe036;',
			'icon-checkmark' : '&#xe037;',
			'icon-x-altx-alt' : '&#xe038;',
			'icon-fullscreen-exit' : '&#xe039;',
			'icon-fullscreen-exit-alt' : '&#xe03a;',
			'icon-fullscreen' : '&#xe03b;',
			'icon-fullscreen-alt' : '&#xe03c;',
			'icon-info' : '&#xe03d;',
			'icon-minus-alt' : '&#xe03e;',
			'icon-plus-alt' : '&#xe040;',
			'icon-plus' : '&#xe03f;',
			'icon-minus' : '&#xe041;',
			'icon-transfer' : '&#xe042;',
			'icon-move-vertical' : '&#xe044;',
			'icon-mail' : '&#xe043;',
			'icon-heart-stroke' : '&#xe045;',
			'icon-heart-fill' : '&#xe046;',
			'icon-movie' : '&#xe047;',
			'icon-arrow-up-2' : '&#xe048;',
			'icon-arrow-right-2' : '&#xe049;',
			'icon-arrow-down-2' : '&#xe04a;',
			'icon-arrow-left-2' : '&#xe04b;',
			'icon-arrow-up-3' : '&#xe04c;',
			'icon-arrow-right-3' : '&#xe04d;',
			'icon-arrow-down-3' : '&#xe04e;',
			'icon-arrow-left-3' : '&#xe04f;',
			'icon-checkbox-checked' : '&#xe050;',
			'icon-checkbox-unchecked' : '&#xe051;',
			'icon-checkbox-partial' : '&#xe052;',
			'icon-radio-checked' : '&#xe053;',
			'icon-radio-unchecked' : '&#xe054;',
			'icon-star' : '&#xe055;',
			'icon-star-2' : '&#xe056;',
			'icon-star-3' : '&#xe057;',
			'icon-cog' : '&#xe058;',
			'icon-cogs' : '&#xe059;',
			'icon-cog-2' : '&#xe05a;',
			'icon-spinner' : '&#xe05b;',
			'icon-expand' : '&#xe05c;',
			'icon-contract' : '&#xe05d;',
			'icon-expand-2' : '&#xe05e;',
			'icon-contract-2' : '&#xe05f;',
			'icon-zoom-in' : '&#xe060;',
			'icon-zoom-out' : '&#xe061;',
			'icon-user' : '&#xe062;',
			'icon-users' : '&#xe063;',
			'icon-lock' : '&#xe064;',
			'icon-lock-2' : '&#xe065;',
			'icon-unlocked' : '&#xe066;',
			'icon-wrench' : '&#xe067;',
			'icon-settings' : '&#xe068;',
			'icon-equalizer' : '&#xe069;',
			'icon-user-2' : '&#xe06a;',
			'icon-home' : '&#xe06b;',
			'icon-camera-2' : '&#xe06c;',
			'icon-images' : '&#xe06d;',
			'icon-music' : '&#xe06e;',
			'icon-headphones' : '&#xe06f;',
			'icon-play' : '&#xe070;',
			'icon-address-book' : '&#xe071;',
			'icon-qrcode' : '&#xe072;',
			'icon-disk' : '&#xe073;',
			'icon-rocket' : '&#xe074;',
			'icon-compass' : '&#xe075;',
			'icon-camera-3' : '&#xe076;',
			'icon-group' : '&#xf0c0;',
			'icon-link' : '&#xf0c1;',
			'icon-alert' : '&#xe077;',
			'icon-comment-2' : '&#xe078;',
			'icon-google' : '&#xe079;',
			'icon-google-plus' : '&#xe07a;',
			'icon-google-plus-2' : '&#xe07b;',
			'icon-google-plus-3' : '&#xe07c;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};